[env:xiao-nrf52840-plus]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-afruitnrf52-nrf52840
framework = arduino
monitor_speed = 115200
build_flags =
  -I${PROJECT_DIR}
lib_archive = no
